const NODE_TOKEN_TESTNET="";
const NODE_ENDPOINT_TESTNET="https://node.testnet.algoexplorerapi.io";
const NODE_PORT_TESTNET=443;
const INDEXER_TOKEN_TESTNET="";
const INDEXER_ENDPOINT_TESTNET="https://algoindexer.testnet.algoexplorerapi.io";
const INDEXER_PORT_TESTNET=443;

const NODE_TOKEN_MAINNET="";
const NODE_ENDPOINT_MAINNET="https://node.algoexplorerapi.io";
const NODE_PORT_MAINNET=443;
const INDEXER_TOKEN_MAINNET="";
const INDEXER_ENDPOINT_MAINNET="https://algoindexer.algoexplorerapi.io";
const INDEXER_PORT_MAINNET=443;

module.exports = {
    NODE_TOKEN_TESTNET,
    NODE_ENDPOINT_TESTNET,
    NODE_PORT_TESTNET,
    INDEXER_TOKEN_TESTNET,
    INDEXER_ENDPOINT_TESTNET,
    INDEXER_PORT_TESTNET,
    NODE_TOKEN_MAINNET,
    NODE_ENDPOINT_MAINNET,
    NODE_PORT_MAINNET,
    INDEXER_TOKEN_MAINNET,
    INDEXER_ENDPOINT_MAINNET,
    INDEXER_PORT_MAINNET
}